---
title: "Causes of Internal Migration in Turkey"
author: 
  - Gelir, Hacer[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080484, [Github Repo](https://github.com/hacergelir7/Midterm)

# Important Information About Midterm

\colorbox{BurntOrange}{WRITE YOUR GITHUB REPO LINK ON LINE 35 IN THIS FILE!}

**Project Proposal submisson will be done by uploading a zip file to the ekampus system along with the Github repo link. If you do not upload a zip file to the system and do not provide a Github repo link, you will be deemed not to have entered the midterm and final exams.**

**You must upload your project folder (`YourStudentID.zip` file) to *ekampus.ankara.edu.tr* until 16 April 2023, 23:59.**

\colorbox{WildStrawberry}{Read the README.md file in the project folder for more information.}

# Introduction

With the earthquake disaster experienced in recent days, the population in the provinces located in the earthquake zone has become a hot topic. The high population density of our city, which has a high risk of earthquakes such as Istanbul, Izmir and Kocaeli, has led the state and large companies to take action.

Internal migration is the main reason why some cities host more population than others. Internal migration causes many desirable and undesirable situations within the country. States have followed different policies in this regard at different times.

In this study, we will talk about the concept of internal migration, its causes, consequences and possible suggestions, and we will make use of the 2018-2021 Inter-Provincial Migration data shared by TUIK while talking about the reasons for migration.

## Literature Review

Migration and internal migration are phenomena as old as human history. Causes such as war, famine and thirst are the reasons for people to migrate in the past [@shaohua:2005]. Today, besides these basic reasons, there are also some reasons brought by modern life. These can be counted as urbanization, unemployment, the desire to increase the level of welfare, access to education and most importantly, globalization.

Migration in our country gained momentum after 1950 and the direction of migration is generally from rural to urban [@sen:2014]. The people living in the countryside and engaged in agriculture suffer from inefficient irrigation, agricultural machinery, global warming, etc. and for these reasons, they could not get as much efficiency from the land as before and could not make a living. For this reason, they started to work as factory workers or low-qualified service sector workers in the big cities of Turkey and European countries [@bostan:2017]. Although European countries employed these migrant workers within the framework of certain rules and distributed them to accommodation places, Turkey could not achieve this and became increasingly irregularly urbanized. At the same time, the rate of unregistered workers has increased and workers have not been educated about their union rights and few of them have been able to use these rights.

Industrial society and the economic development thanks to it have caused internal migration in other countries as well as in our country. One of them is China. In China, as in our country, it has been tried to deal with irregular urbanization and its problems for a long time.

The most effective way to combat internal migration is to have equal job opportunities all over the country, in addition to public services such as education, health and transportation, which can be accessed under equal conditions throughout the country [@tacskesen:2017].



**References section is created automatically by Rmarkdown. There is no need to change the references section in the draft file.**

**_You shouldn't delete the last 3 lines. Those lines are required for References section._**

\newpage
# References {#references}
<div id="refs"></div>

